apiVersion: apps/v1
kind: Deployment
metadata: 
  name: my-deployment
  namespace: production
  labels:
    app: travelling-app
    type : front-end
spec:
  replicas: 4
  selector:
    matchLabels:
      app: my-pod-app
  template:
    metadata:
      name: travelling-pod
      labels:
        app: my-pod-app
    spec:
      containers:
       - name: my-container
         image: madhavkp/travelling-gcp-img
         ports:
         - containerPort: 8080
         resources:
           requests:
             memory: 64Mi
             cpu: 250m
           limits: 
             memory: 128Mi
         command: ["bin/bash"]
         args: ["-c","/root/apache-tomcat-9.0.83/bin/startup.sh; while true; do sleep 1; done;"]
         envFrom:
         - configMapRef:
             name: app-config
